select DATE_FORMAT(A.SALES_DATE,"%Y-%m-%d") AS SALES_DATE,A.PRODUCT_ID,A.USER_ID,A.SALES_AMOUNT
FROM  ONLINE_SALE AS A
where A.sales_date >= '2022-03-01' and A.sales_date < '2022-04-01'
union all
select DATE_FORMAT(B.SALES_DATE,"%Y-%m-%d") AS SALES_DATE,B.PRODUCT_ID,NULL AS USER_ID,B.SALES_AMOUNT
FROM OFFLINE_SALE AS B
WHERE B.sales_date >= '2022-03-01' and B.sales_date < '2022-04-01'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
;