-- 코드를 입력하세요
SELECT A.WRITER_ID AS USER_ID,B.NICKNAME,SUM(A.price) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS A
LEFT JOIN USED_GOODS_USER AS B
ON A.WRITER_ID=B.USER_ID
WHERE STATUS='DONE'
GROUP BY A.WRITER_ID
HAVING SUM(A.price)>=700000
ORDER BY TOTAL_SALES;